// <auto-generated />
using DoAn.Areas.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoAn.Migrations
{
    [DbContext(typeof(DPContext))]
    [Migration("20201201113500_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DoAn.Areas.Admin.Models.DienThoaiModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<string>("DongDTMaDT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("GiaKM")
                        .HasColumnType("real");

                    b.Property<string>("Hinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDongDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDongDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DongDTMaDT");

                    b.ToTable("DienThoai");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.DongDienThoaiModel", b =>
                {
                    b.Property<string>("MaDT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenDongDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDT");

                    b.ToTable("DongDienThoai");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.DienThoaiModel", b =>
                {
                    b.HasOne("DoAn.Areas.Admin.Models.DongDienThoaiModel", "DongDT")
                        .WithMany("listDienThoai")
                        .HasForeignKey("DongDTMaDT");

                    b.Navigation("DongDT");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.DongDienThoaiModel", b =>
                {
                    b.Navigation("listDienThoai");
                });
#pragma warning restore 612, 618
        }
    }
}
