// <auto-generated />
using System;
using DoAn.Areas.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoAn.Migrations
{
    [DbContext(typeof(DPContext))]
    partial class DPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DoAn.Areas.Admin.Models.ChiTietHoaDonModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<float>("GiaKhuyenMai")
                        .HasColumnType("real");

                    b.Property<int>("IDDienThoai")
                        .HasColumnType("int");

                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDDienThoai");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.DienThoaiModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<float>("GiaKM")
                        .HasColumnType("real");

                    b.Property<string>("Hinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDongDT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MaDongDT");

                    b.ToTable("DienThoai");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.DongDienThoaiModel", b =>
                {
                    b.Property<string>("MaDT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenDongDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDT");

                    b.ToTable("DongDienThoai");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.Property<string>("MaHD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayLapHD")
                        .HasColumnType("datetime2");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.HasKey("MaHD");

                    b.HasIndex("MaTK");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.TaiKhoanModel", b =>
                {
                    b.Property<string>("TenTK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LoaiTK")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenTK");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.ChiTietHoaDonModel", b =>
                {
                    b.HasOne("DoAn.Areas.Admin.Models.DienThoaiModel", "DienThoai")
                        .WithMany("listDTCoHoaDon")
                        .HasForeignKey("IDDienThoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Areas.Admin.Models.HoaDonModel", "HoaDon")
                        .WithMany("listChiTiet")
                        .HasForeignKey("MaHoaDon");

                    b.Navigation("DienThoai");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.DienThoaiModel", b =>
                {
                    b.HasOne("DoAn.Areas.Admin.Models.DongDienThoaiModel", "DongDT")
                        .WithMany("listDienThoai")
                        .HasForeignKey("MaDongDT");

                    b.Navigation("DongDT");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.HasOne("DoAn.Areas.Admin.Models.TaiKhoanModel", "TaiKhoan")
                        .WithMany("listHoaDon")
                        .HasForeignKey("MaTK");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.DienThoaiModel", b =>
                {
                    b.Navigation("listDTCoHoaDon");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.DongDienThoaiModel", b =>
                {
                    b.Navigation("listDienThoai");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.Navigation("listChiTiet");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.TaiKhoanModel", b =>
                {
                    b.Navigation("listHoaDon");
                });
#pragma warning restore 612, 618
        }
    }
}
